version: '3.8'
services:
  web:
    build:
      context: .
    ports:
      - "80:80"
    environment:
      - DB_HOST=timofemh.beget.tech
      - DB_PORT=localhost
      - DB_NAME=timofemh_auth
      - DB_USERNAME=timofemh_auth
      - DB_PASSWORD=32Belizu32!
